import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <nav className=" flex ">
          <h3>Shop</h3>

          <Link href="/">Home</Link>
          <Link href="/tickets">Tickets</Link>


          <h1>Data from Layout can be seen in every dependent PAge</h1>
        </nav>


        {children}</body>
    </html>
  );
}
